export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_ROOMS_PENDING = 'FETCH_ROOMS_PENDING';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';

export const SET_ACTIVE_ROOM_ID = 'SET_ACTIVE_ROOM_ID';
export const SET_ACTIVE_ROOM_USERS = 'SET_ACTIVE_ROOM_USERS';
export const FETCH_ROOM_USERS_SUCCESS = 'FETCH_ROOM_USERS_SUCCESS';
export const FETCH_ROOM_USERS_ERROR = 'FETCH_ROOM_USERS_ERROR';

export const SET_ACTIVE_ROOM_STATUS_PENDING = 'SET_ACTIVE_ROOM_STATUS_PENDING';
export const SET_ACTIVE_ROOM_STATUS_SUCCESS = 'SET_ACTIVE_ROOM_STATUS_SUCCESS';
export const SET_ACTIVE_ROOM_STATUS_ERROR = 'SET_ACTIVE_ROOM_STATUS_ERROR';

export const SET_MESSAGE = 'SET_MESSAGE';
export const LEAVE_CHAT = 'LEAVE_CHAT';
export const FETCH_ROOMS_MESSAGES_SUCCESS = 'FETCH_ROOMS_MESSAGES_SUCCESS';